<a href="https://colab.research.google.com/github/PyinDS/DSBC/blob/main/02_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Instalacja biblioteki NumPy

In [7]:
pip install numpy

Importowanie biblioteki NumPy i sprawdzenie wersji

In [9]:
import numpy as np
np.__version__

'1.19.5'

Wyświetlenie zawartości numpy

In [ ]:
print(dir(np))

Wyświetlenie pomocy dla tablicy array

In [ ]:
help(np.array)

Tablica jenowymiarowa 1D Array

In [13]:
x = np.array([1,3])
x

array([1, 3])

In [14]:
print(x)

[1 3]


In [15]:
type(x)

numpy.ndarray

In [19]:
# wyświetlenie wymiaru tablicy
x.ndim

1

In [20]:
# wyświetlenie kształtu tablicy
x.shape

(2,)

In [21]:
# wyświetlenie rozmiaru tablicy
x.size

2

In [23]:
# wyświetlenie typu danych
x.dtype

dtype('int64')

In [26]:
# Utworzenie drugiej tablicy
y = np.array([1.3,2.3,1.4])
print(y)

[1.3 2.3 1.4]


In [28]:
# Wyświetleni typu
y.dtype

dtype('float64')

Tablica dwuwymiarowa 2D Array

In [31]:
z = np.array([[1,2],[-3,1]])
z

array([[ 1,  2],
       [-3,  1]])

In [32]:
z.ndim

2

In [33]:
z.shape

(2, 2)

In [35]:
a = np.array([[1,2,4],[4,2,1]])
print(a)

[[1 2 4]
 [4 2 1]]


In [37]:
a.shape

(2, 3)

Macierz trójwymiarowa 3D Array

In [41]:
b = np.array(
  [[[4, 3, 1],
    [3, 1, 2]],
   [[4, 1, 3],
    [4, 2, 1]],
   [[3, 2, 1],
    [4, 3, 2]]]
)
b

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [42]:
b.ndim

3

In [43]:
b.shape

(3, 2, 3)